import { ActivityCategoryConfig } from '@/types/activity';

export const ACTIVITY_CATEGORIES: Record<string, ActivityCategoryConfig> = {
  health: {
    id: 'health',
    name: 'Health & Fitness',
    icon: 'figure.run',
    color: '#FF6B6B',
    basePoints: 30,
    description: 'Physical activities and healthy habits',
  },
  productivity: {
    id: 'productivity',
    name: 'Productivity',
    icon: 'bolt.fill',
    color: '#4ECDC4',
    basePoints: 25,
    description: 'Work, tasks, and getting things done',
  },
  social: {
    id: 'social',
    name: 'Social',
    icon: 'bubble.left.and.bubble.right.fill',
    color: '#FFD93D',
    basePoints: 20,
    description: 'Connecting with friends and family',
  },
  mindfulness: {
    id: 'mindfulness',
    name: 'Mindfulness',
    icon: 'brain.head.profile',
    color: '#95E77E',
    basePoints: 25,
    description: 'Meditation, reflection, and mental wellness',
  },
  creativity: {
    id: 'creativity',
    name: 'Creativity',
    icon: 'wand.and.stars',
    color: '#A8E6CF',
    basePoints: 20,
    description: 'Art, music, writing, and creative expression',
  },
  learning: {
    id: 'learning',
    name: 'Learning',
    icon: 'lightbulb.fill',
    color: '#B4A7D6',
    basePoints: 30,
    description: 'Education, skills, and personal growth',
  },
  adventure: {
    id: 'adventure',
    name: 'Adventure',
    icon: 'airplane.departure',
    color: '#FFA500',
    basePoints: 35,
    description: 'New experiences and exploring',
  },
  'self-care': {
    id: 'self-care',
    name: 'Self Care',
    icon: 'sparkle',
    color: '#FFB6C1',
    basePoints: 20,
    description: 'Rest, relaxation, and treating yourself',
  },
};

export const ACHIEVEMENTS = [
  {
    id: 'first_activity',
    title: 'First Step',
    description: 'Complete your first activity',
    icon: '🎯',
    requirement: { type: 'activities' as const, value: 1 },
  },
  {
    id: 'aura_novice',
    title: 'Aura Novice',
    description: 'Earn 100 aura points',
    icon: '✨',
    requirement: { type: 'points' as const, value: 100 },
  },
  {
    id: 'aura_adept',
    title: 'Aura Adept',
    description: 'Earn 500 aura points',
    icon: '🌟',
    requirement: { type: 'points' as const, value: 500 },
  },
  {
    id: 'aura_master',
    title: 'Aura Master',
    description: 'Earn 1000 aura points',
    icon: '💫',
    requirement: { type: 'points' as const, value: 1000 },
  },
  {
    id: 'week_warrior',
    title: 'Week Warrior',
    description: 'Maintain a 7-day streak',
    icon: '🔥',
    requirement: { type: 'streak' as const, value: 7 },
  },
  {
    id: 'consistency_king',
    title: 'Consistency King',
    description: 'Maintain a 30-day streak',
    icon: '👑',
    requirement: { type: 'streak' as const, value: 30 },
  },
  {
    id: 'health_hero',
    title: 'Health Hero',
    description: 'Complete 10 health activities',
    icon: '💪',
    requirement: { type: 'category' as const, value: 10, category: 'health' },
  },
  {
    id: 'productivity_pro',
    title: 'Productivity Pro',
    description: 'Complete 10 productivity activities',
    icon: '🚀',
    requirement: { type: 'category' as const, value: 10, category: 'productivity' },
  },
];
