/**
 * Predefined Task Library
 * A collection of tasks users can complete to earn aura points
 *
 * Task Structure:
 * - Easy: 10-15 aura points (5-15 min tasks)
 * - Medium: 20-30 aura points (15-45 min tasks)
 * - Hard: 40-60 aura points (45+ min tasks)
 * - Legendary: 80-150 aura points (major achievements)
 */

import { Task, TaskCategory } from '@/types/task';

// Helper to generate task ID
const generateTaskId = (category: string, name: string): string => {
  return `${category}_${name.toLowerCase().replace(/\s+/g, '_')}`;
};

// ===== PHYSICAL TASKS 💪 =====
export const PHYSICAL_TASKS: Task[] = [
  // Easy
  {
    id: generateTaskId('physical', 'walk_10k_steps'),
    title: 'Walk 10,000 Steps',
    description: 'Take 10,000 steps today to boost your physical health',
    category: 'physical',
    difficulty: 'easy',
    auraPoints: 10,
    icon: '🚶',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('physical', 'pushups_20'),
    title: '20 Push-ups',
    description: 'Complete 20 push-ups in one or multiple sets',
    category: 'physical',
    difficulty: 'easy',
    auraPoints: 10,
    icon: '💪',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('physical', 'stretch_10min'),
    title: 'Stretch for 10 Minutes',
    description: 'Improve flexibility with a 10-minute stretching routine',
    category: 'physical',
    difficulty: 'easy',
    auraPoints: 10,
    icon: '🧘',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('physical', 'take_stairs'),
    title: 'Take the Stairs',
    description: 'Choose stairs over elevator throughout the day',
    category: 'physical',
    difficulty: 'easy',
    auraPoints: 5,
    icon: '🪜',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },

  // Medium
  {
    id: generateTaskId('physical', 'workout_30min'),
    title: '30-Minute Workout',
    description: 'Complete a full 30-minute workout session',
    category: 'physical',
    difficulty: 'medium',
    auraPoints: 25,
    icon: '🏋️',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('physical', 'run_2_miles'),
    title: 'Run 2 Miles',
    description: 'Run or jog for 2 miles',
    category: 'physical',
    difficulty: 'medium',
    auraPoints: 25,
    icon: '🏃',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('physical', 'cold_shower'),
    title: 'Take a Cold Shower',
    description: 'End your shower with 2 minutes of cold water',
    category: 'physical',
    difficulty: 'medium',
    auraPoints: 20,
    icon: '🚿',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('physical', 'burpees_100'),
    title: '100 Burpees',
    description: 'Complete 100 burpees (can be broken into sets)',
    category: 'physical',
    difficulty: 'medium',
    auraPoints: 30,
    icon: '🔥',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },

  // Hard
  {
    id: generateTaskId('physical', 'gym_session_full'),
    title: 'Full Gym Session',
    description: 'Complete a comprehensive 60+ minute gym workout',
    category: 'physical',
    difficulty: 'hard',
    auraPoints: 50,
    icon: '💯',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('physical', 'run_5_miles'),
    title: 'Run 5 Miles',
    description: 'Complete a 5-mile run',
    category: 'physical',
    difficulty: 'hard',
    auraPoints: 50,
    icon: '🏃‍♂️',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('physical', 'hiit_workout'),
    title: 'HIIT Workout',
    description: 'Complete a high-intensity interval training session',
    category: 'physical',
    difficulty: 'hard',
    auraPoints: 45,
    icon: '⚡',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },

  // Legendary
  {
    id: generateTaskId('physical', 'marathon'),
    title: 'Complete a Marathon',
    description: 'Finish a full or half marathon',
    category: 'physical',
    difficulty: 'legendary',
    auraPoints: 150,
    icon: '🏆',
    isCustom: false,
    frequency: 'once',
    requiredLevel: 5,
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('physical', 'workout_streak_7'),
    title: '7-Day Workout Streak',
    description: 'Work out every day for 7 consecutive days',
    category: 'physical',
    difficulty: 'legendary',
    auraPoints: 100,
    icon: '🔥',
    isCustom: false,
    frequency: 'once',
    createdAt: Date.now(),
  },
];

// ===== MENTAL TASKS 🧠 =====
export const MENTAL_TASKS: Task[] = [
  // Easy
  {
    id: generateTaskId('mental', 'meditate_5min'),
    title: 'Meditate for 5 Minutes',
    description: 'Practice mindfulness meditation for 5 minutes',
    category: 'mental',
    difficulty: 'easy',
    auraPoints: 10,
    icon: '🧘‍♂️',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('mental', 'read_10_pages'),
    title: 'Read 10 Pages',
    description: 'Read at least 10 pages of a book',
    category: 'mental',
    difficulty: 'easy',
    auraPoints: 10,
    icon: '📖',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('mental', 'gratitude_journal'),
    title: 'Gratitude Journaling',
    description: "Write down 3 things you're grateful for",
    category: 'mental',
    difficulty: 'easy',
    auraPoints: 10,
    icon: '✍️',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('mental', 'learn_vocab'),
    title: 'Learn 5 New Words',
    description: 'Learn and understand 5 new vocabulary words',
    category: 'mental',
    difficulty: 'easy',
    auraPoints: 10,
    icon: '📚',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },

  // Medium
  {
    id: generateTaskId('mental', 'meditate_20min'),
    title: 'Meditate for 20 Minutes',
    description: 'Deep meditation session for 20 minutes',
    category: 'mental',
    difficulty: 'medium',
    auraPoints: 25,
    icon: '🧘',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('mental', 'read_30min'),
    title: 'Read for 30 Minutes',
    description: 'Dedicated reading time for 30 minutes',
    category: 'mental',
    difficulty: 'medium',
    auraPoints: 20,
    icon: '📗',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('mental', 'online_course_lesson'),
    title: 'Complete a Course Lesson',
    description: 'Finish one lesson from an online course',
    category: 'mental',
    difficulty: 'medium',
    auraPoints: 25,
    icon: '🎓',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('mental', 'problem_solving'),
    title: 'Solve Complex Problem',
    description: 'Work on and solve a challenging puzzle or problem',
    category: 'mental',
    difficulty: 'medium',
    auraPoints: 30,
    icon: '🧩',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },

  // Hard
  {
    id: generateTaskId('mental', 'meditate_1hour'),
    title: 'Meditate for 1 Hour',
    description: 'Extended meditation session for 1 full hour',
    category: 'mental',
    difficulty: 'hard',
    auraPoints: 50,
    icon: '🧘‍♀️',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('mental', 'finish_book_chapter'),
    title: 'Finish a Book Chapter',
    description: 'Complete an entire chapter of a book',
    category: 'mental',
    difficulty: 'hard',
    auraPoints: 40,
    icon: '📕',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('mental', 'learn_new_skill'),
    title: 'Learn a New Skill',
    description: 'Spend time learning and practicing a new skill',
    category: 'mental',
    difficulty: 'hard',
    auraPoints: 50,
    icon: '🎯',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },

  // Legendary
  {
    id: generateTaskId('mental', 'complete_certification'),
    title: 'Complete a Certification',
    description: 'Finish a full course or certification program',
    category: 'mental',
    difficulty: 'legendary',
    auraPoints: 150,
    icon: '🏅',
    isCustom: false,
    frequency: 'once',
    requiredLevel: 4,
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('mental', 'finish_entire_book'),
    title: 'Finish an Entire Book',
    description: 'Complete reading a full book from cover to cover',
    category: 'mental',
    difficulty: 'legendary',
    auraPoints: 100,
    icon: '📚',
    isCustom: false,
    frequency: 'once',
    createdAt: Date.now(),
  },
];

// ===== SOCIAL TASKS 🤝 =====
export const SOCIAL_TASKS: Task[] = [
  // Easy
  {
    id: generateTaskId('social', 'call_friend'),
    title: 'Call a Friend',
    description: 'Have a phone or video call with a friend or family member',
    category: 'social',
    difficulty: 'easy',
    auraPoints: 10,
    icon: '📞',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('social', 'give_compliment'),
    title: 'Give a Genuine Compliment',
    description: 'Give someone a heartfelt, genuine compliment',
    category: 'social',
    difficulty: 'easy',
    auraPoints: 10,
    icon: '💝',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('social', 'help_someone'),
    title: 'Help Someone',
    description: 'Offer help or assistance to someone who needs it',
    category: 'social',
    difficulty: 'easy',
    auraPoints: 15,
    icon: '🤲',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },

  // Medium
  {
    id: generateTaskId('social', 'meaningful_conversation'),
    title: 'Meaningful Conversation',
    description: 'Have a deep, meaningful conversation (30+ minutes)',
    category: 'social',
    difficulty: 'medium',
    auraPoints: 25,
    icon: '💬',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('social', 'network_new_person'),
    title: 'Network with Someone New',
    description: 'Meet and connect with a new person',
    category: 'social',
    difficulty: 'medium',
    auraPoints: 30,
    icon: '🤝',
    isCustom: false,
    frequency: 'weekly',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('social', 'volunteer'),
    title: 'Volunteer Your Time',
    description: 'Spend time volunteering for a cause',
    category: 'social',
    difficulty: 'medium',
    auraPoints: 30,
    icon: '❤️',
    isCustom: false,
    frequency: 'weekly',
    createdAt: Date.now(),
  },

  // Hard
  {
    id: generateTaskId('social', 'organize_gathering'),
    title: 'Organize a Social Gathering',
    description: 'Plan and host a social event with friends',
    category: 'social',
    difficulty: 'hard',
    auraPoints: 50,
    icon: '🎉',
    isCustom: false,
    frequency: 'weekly',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('social', 'mentor_someone'),
    title: 'Mentor Someone',
    description: 'Spend time mentoring or teaching someone',
    category: 'social',
    difficulty: 'hard',
    auraPoints: 50,
    icon: '👨‍🏫',
    isCustom: false,
    frequency: 'weekly',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('social', 'public_speaking'),
    title: 'Public Speaking',
    description: 'Give a presentation or speak in front of a group',
    category: 'social',
    difficulty: 'hard',
    auraPoints: 60,
    icon: '🎤',
    isCustom: false,
    frequency: 'once',
    createdAt: Date.now(),
  },
];

// ===== PRODUCTIVITY TASKS 📊 =====
export const PRODUCTIVITY_TASKS: Task[] = [
  // Easy
  {
    id: generateTaskId('productivity', 'make_bed'),
    title: 'Make Your Bed',
    description: 'Start your day by making your bed',
    category: 'productivity',
    difficulty: 'easy',
    auraPoints: 5,
    icon: '🛏️',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('productivity', 'plan_day'),
    title: 'Plan Your Day',
    description: 'Create a plan or to-do list for the day',
    category: 'productivity',
    difficulty: 'easy',
    auraPoints: 10,
    icon: '📝',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('productivity', 'clean_workspace'),
    title: 'Clean Your Workspace',
    description: 'Organize and clean your work area',
    category: 'productivity',
    difficulty: 'easy',
    auraPoints: 10,
    icon: '🧹',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('productivity', 'inbox_zero'),
    title: 'Inbox Zero',
    description: 'Clear all emails from your inbox',
    category: 'productivity',
    difficulty: 'easy',
    auraPoints: 15,
    icon: '📧',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },

  // Medium
  {
    id: generateTaskId('productivity', 'complete_3_tasks'),
    title: 'Complete 3 Important Tasks',
    description: 'Finish 3 high-priority tasks from your to-do list',
    category: 'productivity',
    difficulty: 'medium',
    auraPoints: 25,
    icon: '✅',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('productivity', 'deep_work_2hours'),
    title: 'Deep Work - 2 Hours',
    description: 'Focused work session for 2 hours without distractions',
    category: 'productivity',
    difficulty: 'medium',
    auraPoints: 30,
    icon: '🎯',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('productivity', 'organize_week'),
    title: 'Organize Your Week',
    description: 'Plan and schedule your entire week ahead',
    category: 'productivity',
    difficulty: 'medium',
    auraPoints: 25,
    icon: '📅',
    isCustom: false,
    frequency: 'weekly',
    createdAt: Date.now(),
  },

  // Hard
  {
    id: generateTaskId('productivity', 'project_milestone'),
    title: 'Complete Project Milestone',
    description: 'Finish a major milestone in a project',
    category: 'productivity',
    difficulty: 'hard',
    auraPoints: 50,
    icon: '🏁',
    isCustom: false,
    frequency: 'weekly',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('productivity', 'deep_work_4hours'),
    title: 'Deep Work - 4+ Hours',
    description: 'Extended focused work session (4+ hours)',
    category: 'productivity',
    difficulty: 'hard',
    auraPoints: 60,
    icon: '🔥',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },

  // Legendary
  {
    id: generateTaskId('productivity', 'launch_project'),
    title: 'Launch a Project',
    description: 'Complete and launch a major project',
    category: 'productivity',
    difficulty: 'legendary',
    auraPoints: 150,
    icon: '🚀',
    isCustom: false,
    frequency: 'once',
    requiredLevel: 5,
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('productivity', 'perfect_week'),
    title: 'Perfect Productivity Week',
    description: 'Maintain peak productivity for 7 consecutive days',
    category: 'productivity',
    difficulty: 'legendary',
    auraPoints: 100,
    icon: '👑',
    isCustom: false,
    frequency: 'once',
    createdAt: Date.now(),
  },
];

// ===== HABIT TASKS 🌱 =====
export const HABIT_TASKS: Task[] = [
  // Easy
  {
    id: generateTaskId('habits', 'wake_early'),
    title: 'Wake Up Before 7 AM',
    description: 'Start your day early by waking up before 7 AM',
    category: 'habits',
    difficulty: 'easy',
    auraPoints: 10,
    icon: '🌅',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('habits', 'no_phone_morning'),
    title: 'No Phone First Hour',
    description: 'Avoid using your phone for the first hour after waking',
    category: 'habits',
    difficulty: 'easy',
    auraPoints: 15,
    icon: '📵',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('habits', 'drink_water'),
    title: 'Drink 8 Glasses of Water',
    description: 'Stay hydrated by drinking at least 8 glasses of water',
    category: 'habits',
    difficulty: 'easy',
    auraPoints: 10,
    icon: '💧',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('habits', 'sleep_early'),
    title: 'Sleep Before 11 PM',
    description: 'Get to bed before 11 PM for quality sleep',
    category: 'habits',
    difficulty: 'easy',
    auraPoints: 10,
    icon: '😴',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },

  // Medium
  {
    id: generateTaskId('habits', 'morning_routine'),
    title: 'Complete Morning Routine',
    description: 'Follow your complete morning routine without skipping',
    category: 'habits',
    difficulty: 'medium',
    auraPoints: 25,
    icon: '☀️',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('habits', 'no_social_media'),
    title: 'No Social Media Day',
    description: 'Go the entire day without using social media',
    category: 'habits',
    difficulty: 'medium',
    auraPoints: 30,
    icon: '🚫',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('habits', 'track_nutrition'),
    title: 'Track All Meals',
    description: 'Log and track all your meals and nutrition',
    category: 'habits',
    difficulty: 'medium',
    auraPoints: 20,
    icon: '🍽️',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },

  // Hard
  {
    id: generateTaskId('habits', 'perfect_day'),
    title: 'Perfect Day',
    description: 'Complete all your daily habits without fail',
    category: 'habits',
    difficulty: 'hard',
    auraPoints: 50,
    icon: '💯',
    isCustom: false,
    frequency: 'daily',
    createdAt: Date.now(),
  },
  {
    id: generateTaskId('habits', 'digital_detox'),
    title: 'Digital Detox Weekend',
    description: 'Spend the entire weekend without digital distractions',
    category: 'habits',
    difficulty: 'hard',
    auraPoints: 60,
    icon: '📵',
    isCustom: false,
    frequency: 'weekly',
    createdAt: Date.now(),
  },
];

// ===== MASTER TASK LIBRARY =====
export const ALL_TASKS: Task[] = [
  ...PHYSICAL_TASKS,
  ...MENTAL_TASKS,
  ...SOCIAL_TASKS,
  ...PRODUCTIVITY_TASKS,
  ...HABIT_TASKS,
];

// Helper functions
export const getTasksByCategory = (category: TaskCategory): Task[] => {
  return ALL_TASKS.filter((task) => task.category === category);
};

export const getTasksByDifficulty = (difficulty: string): Task[] => {
  return ALL_TASKS.filter((task) => task.difficulty === difficulty);
};

export const getTaskById = (id: string): Task | undefined => {
  return ALL_TASKS.find((task) => task.id === id);
};

export const getRandomDailyTasks = (count: number = 5): Task[] => {
  const shuffled = [...ALL_TASKS].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
};
